### ISSUE TITLE
change help text

### ISSUE THREAD

**Issue by rhicu** [rhicu/rift-discord-bot#5]
QoL help meldung bot:
usage:

help - show this message

1. Create your Character, you have to do this once for every raiding charakter.
create <name@shard> <class> <roles> <shortName>
   e.g.: 'create Paxie@Brutwacht Kleriker Tank,DD,Heal,Support Pax'

2. Register your character for incoming raid 
register <raidID> <shortName>
     e.g. 'register 1001 Pax'

3. Deregister your character for incoming raid:
deregister <raidID>
    e.g. 'deregister 1003'

Admin Settings:
addRaid <irotp / td> <day> <date>
printRaids
deleteRaid <irotp / td> <day>
updateRaid <irotp / td> <day> <day / date / start / end / invite> <data>
clearRaidChannel

**Comment by rhicu** [comment]
fix: https://github.com/rhicu/RiftDiscordBot/commit/7e249db8c2873337db8d162a391f4b41c88ad30b

**Comment by whitekb** [comment]
Added review comment to commit.
Can be merged to Master.
