### ISSUE TITLE
It should be possible to unregister without registering beforehand

### ISSUE THREAD

**Issue by rhicu** [rhicu/rift-discord-bot#7]
As a user I want to show that I don't have time for an event and not just forgot about it by directly unregister from it.

**Comment by Paxxie** [comment]
Ich bezweifel sehr stark, dass diese Funktion genutzt werden würde. 
Das würde bedeuten, dass _jeder_ der nichts damit zu tun hat von seiner Seite aus aktiv werden müsste.
Aber dennoch kann ich die Ambition nachvollziehen, dass man Anzeigen möchte, dass man sich aktiv gegen Event XY entschieden hat.

Stattdessen würde ich vorschlagen, dass man Personen anzeigt, die auf "Abruf" sind. Mit anderen Worten man steht zur Verfügung, nimmt per se nicht am Event XY teil, lässt anderen den Vortritt und springt bei Bedarf ein.
